org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.20.2)
forge_version=47.4.10
forge_version_range=[47.4.10,48)
loader_version_range=[47,48)
mapping_channel=official
mapping_version=1.20.1

mod_id=sealedwordorb
mod_name=\u7F04\u8A00\u73E0 / Sealed Word Orb
mod_license=All Rights Reserved
mod_version=1.0.0
mod_group_id=com.sealedwordorb
mod_authors=
mod_description=\u5C06\u6307\u4EE4\u3001\u6743\u9650\u7B49\u7EA7\u548C\u63CF\u8FF0\u5C01\u5B58\u4E8E\u7F04\u8A00\u73E0\uFF0C\u53F3\u952E\u5373\u53EF\u6267\u884C\u3002 Inscribe a command, permission level and description into a Sealed Word Orb, then right-click to execute it.
